from src.database.db_instance import db_handler

db_handler.setTags(book_title="Сто лет одиночества", tags=["NOV", "SAGA", "FIC"])
db_handler.setTags(book_title="451 градус по Фаренгейту", tags=["NOV", "SF", "DYS_LIT", "POL_SF"])
db_handler.setTags(book_title="Маленький принц", tags=["NOVELLA", "CH_LIT", "FIC", "SF"])
db_handler.setTags(book_title="Над пропастью во ржи", tags=["NOV", "1ST_PER", "YA_LIT", "COMING_AGE", "BILD_ROM"])
db_handler.setTags(book_title="Мастер и Маргарита", tags=["NOV", "FANT", "SAT", "FIC", "ROM"])
db_handler.setTags(book_title="Тихий Дон", tags=["NOV"])
db_handler.setTags(book_title="Собачье сердце", tags=["SAT", "SF", "DYS_LIT"])
db_handler.setTags(book_title="На Западном фронте без перемен", tags=["NOV", "WAR_FIC"])
db_handler.setTags(book_title="Война и мир", tags=["NOV", "ROM", "WAR_FIC", "HIST_GEN", "PHIL", "HIST_GEN", "EPOPEE"])
db_handler.setTags(book_title="Отверженные", tags=["NOV", "DRM", "HIST_GEN", "EPOPEE", "ADV_FIC"])
db_handler.setTags(book_title="Гордость и предубеждение", tags=["SAT", "ROM", "FICTION"])
db_handler.setTags(book_title="Унесённые ветром", tags=["NOV", "EPOPEE", "FICTION"])
db_handler.setTags(book_title="Приключения Тома Сойера", tags=["NOV", "CH_LIT", "SAT", "BILD_ROM", "ADV_FIC", "FOLK"])
db_handler.setTags(book_title="Робинзон Крузо", tags=["NOV", "ADV_FIC", "HIST_GEN"])
db_handler.setTags(book_title="Маленькие женщины", tags=["NOV", "CH_LIT", "COM", "DOM_FIC", "FICTION"])
db_handler.setTags(book_title="Белая гвардия", tags=["NOV", "HIST_GEN"])
db_handler.setTags(book_title="Сага о Форсайтах", tags=["NOV", "ROM", "HIST_GEN", "DOM_FIC", "SAGA"])
db_handler.setTags(book_title="Мартин Иден", tags=["NOV", "BILD_ROM", "FAB", "ART_NOV", "FICTION"])
db_handler.setTags(book_title="Жизнь взаймы", tags=["ROM", "FICTION"])
db_handler.setTags(book_title="Время жить и время умирать", tags=["FICTION"])
db_handler.setTags(book_title="Госпожа Бовари", tags=["NOV", "FICTION", "PSY_REAL"])
db_handler.setTags(book_title="Все сказки Ганса Христиана Андерсена", tags=["FICTION", "CH_LIT"])
db_handler.setTags(book_title="Портрет Дориана Грея", tags=["GOTH_LIT", "PSY_REAL"])
db_handler.setTags(book_title="Дон Кихот", tags=["SAT", "PSY_REAL", "ADV_FIC"])
db_handler.setTags(book_title="Джейн Эйр", tags=["NOV", "ROM", "BILD_ROM", "ABN"])
db_handler.setTags(book_title="Двенадцать стульев", tags=["NOV", "SAT", "FICTION"])
db_handler.setTags(book_title="Собор Парижской Богоматери", tags=["NOV", "DRM", "FICTION"])
db_handler.setTags(book_title="Обломов", tags=["NOV", "SAT", "FICTION"])
db_handler.setTags(book_title="Приключения Незнайки и его друзей", tags=["FAIRY", "CH_LIT"])
db_handler.setTags(book_title="Три мушкетёра", tags=["HIST_GEN", "ADV_FIC"])
db_handler.setTags(book_title="Судьба человека", tags=["FICTION"])
db_handler.setTags(book_title="Ярмарка тщеславия", tags=["NOV", "FICTION"])
db_handler.setTags(book_title="Герой нашего времени", tags=["NOV", "PSY_REAL"])
db_handler.setTags(book_title="Остров сокровищ", tags=["NOV", "ADV_FIC", "YA_LIT"])
db_handler.setTags(book_title="Идиот", tags=["NOV"])
db_handler.setTags(book_title="Белый Клык", tags=["NOV", "ADV_FIC"])
db_handler.setTags(book_title="Мёртвые души", tags=["NOV", "SAT", "FICTION"])
db_handler.setTags(book_title="Божественная комедия", tags=["EPIC"])
db_handler.setTags(book_title="Приключения Гекльберри Финна", tags=["NOV", "ADV_FIC", "CH_LIT", "SAT", "HIST_GEN", "BILD_ROM"])
db_handler.setTags(book_title="Дары волхвов", tags=["STORY", "FICTION"])
db_handler.setTags(book_title="Ревизор", tags=["COM"])
db_handler.setTags(book_title="Преступление и наказание", tags=["NOV", "PSY_REAL", "CRIME_GEN", "PHIL"])
db_handler.setTags(book_title="Приключения Оливера Твиста", tags=["NOV", "NOV", "ART_NOV"])
db_handler.setTags(book_title="А зори здесь тихие…", tags=["WAR_FIC", "HIST_GEN"])
db_handler.setTags(book_title="Отцы и дети", tags=["NOV", "ROM", "PHIL", "POL_SF"])
db_handler.setTags(book_title="Фауст", tags=["TRAG"])
db_handler.setTags(book_title="Недоросль", tags=["COM"])
db_handler.setTags(book_title="Тёмные аллеи", tags=["STORY", "FICTION"])
db_handler.setTags(book_title="Тысяча и одна ночь", tags=["FICTION", "FOLK", "FAIRY"])
db_handler.setTags(book_title="Всадник без головы", tags=["NOV", "ADV_FIC"])
db_handler.setTags(book_title="Франкенштейн, или Современный Прометей", tags=["SCI", "SF", "HOR", "GOTH_LIT"])
db_handler.setTags(book_title="Господа Головлевы", tags=["SAT"])
db_handler.setTags(book_title="Униженные и оскорбленные", tags=["NOV", "FICTION"])
db_handler.setTags(book_title="Алые паруса", tags=["FICTION"])
db_handler.setTags(book_title="Руслан и Людмила", tags=["EPIC"])
db_handler.setTags(book_title="Записки охотника", tags=["FICTION"])
db_handler.setTags(book_title="Чайка", tags=["NOVELLA"])
db_handler.setTags(book_title="Человек-амфибия", tags=["NOV", "SF"])
db_handler.setTags(book_title="Дворянское гнездо", tags=["ROM", "POL_SF"])
db_handler.setTags(book_title="Вечера на хуторе близ Диканьки", tags=["FICTION"])
db_handler.setTags(book_title="Король Лир", tags=["TRAG"])
db_handler.setTags(book_title="Красное и черное", tags=["NOV", "PSY_REAL", "BILD_ROM", "HIST_GEN"])
db_handler.setTags(book_title="1984", tags=["SF", "POL_SF", "FIC", "DYS_LIT"])
db_handler.setTags(book_title="Последний из могикан", tags=["NOV", "HIST_GEN", "ADV_FIC"])
db_handler.setTags(book_title="Алиса в Стране Чудес", tags=["DRM", "ADV_FIC", "CH_LIT", "FANT"])
db_handler.setTags(book_title="Макбет", tags=["TRAG"])
db_handler.setTags(book_title="Принц и нищий", tags=["NOV", "CH_LIT", "FANT"])
db_handler.setTags(book_title="Большие надежды", tags=["NOV", "BILD_ROM", "GOTH_LIT", "ABN"])
db_handler.setTags(book_title="Тарас Бульба", tags=["NOVELLA", "ROM", "HIST_GEN"])
db_handler.setTags(book_title="Гамлет, принц датский", tags=["TRAG", "DRM"])
db_handler.setTags(book_title="Повести Белкина. Пиковая дама", tags=["FICTION"])
db_handler.setTags(book_title="Граф Монте-Кристо", tags=["NOV", "ROM", "HIST_GEN", "ADV_FIC"])
db_handler.setTags(book_title="Шинель", tags=["FICTION"])
db_handler.setTags(book_title="Пикник на обочине", tags=["SF", "PHIL"])
db_handler.setTags(book_title="Таинственный остров", tags=["NOV", "ADV_FIC"])
db_handler.setTags(book_title="Вишневый сад", tags=["COM"])
db_handler.setTags(book_title="Волшебник Изумрудного города", tags=["CH_LIT", "FANT"])
db_handler.setTags(book_title="Рождественская песнь в прозе", tags=["FICTION", "NOVELLA", "FAIRY"])
db_handler.setTags(book_title="Горе от ума", tags=["COM"])
db_handler.setTags(book_title="Двенадцать", tags=["POETRY"])
db_handler.setTags(book_title="Пигмалион", tags=["COM"])
db_handler.setTags(book_title="Последнее дело Холмса", tags=["DET"])
db_handler.setTags(book_title="Евгений Онегин", tags=["NOV"])
db_handler.setTags(book_title="Похождения бравого солдата Швейка", tags=["NOV", "SAT", "FICTION", "BLK_HUM"])
db_handler.setTags(book_title="История Дэвида Копперфилда", tags=["COM", "DRM", "ADV_FIC"])
db_handler.setTags(book_title="Слово о полку Игореве", tags=["POETRY", "EPIC"])
db_handler.setTags(book_title="Золотой теленок", tags=["NOV", "SAT", "FICTION"])
db_handler.setTags(book_title="Лолита", tags=["TRAG", "EROT_LIT", "NOV", "COM"])
db_handler.setTags(book_title="Великий Гэтсби", tags=["NOV"])
db_handler.setTags(book_title="О дивный новый мир", tags=["NOV", "SF", "DYS_LIT"])
db_handler.setTags(book_title="Властелин колец", tags=["FANT", "ADV_FIC", "EP_FANT", "KNIGHT_ROM", "HF"])
db_handler.setTags(book_title="Заводной апельсин", tags=["NOV", "SF", "DRM", "DYS_LIT", "NOVELLA", "BLK_HUM", "SAT"])
db_handler.setTags(book_title="Повелитель мух", tags=["NOV", "PSY_REAL", "YA_LIT"])
db_handler.setTags(book_title="Гарри Поттер и философский камень", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и Тайная комната", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и узник Азкабана", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и Кубок огня", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и Орден Феникса", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и Принц-полукровка", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
db_handler.setTags(book_title="Гарри Поттер и Дары Смерти", tags=["NOV", "FANT", "EP_FANT", "YA_LIT", "CH_LIT", "BILD_ROM"])
