INSERT INTO "tag" VALUES
(gen_random_uuid(), 'ABN', 'автобиографический роман'),
(gen_random_uuid(), 'DYS_LIT', 'антиутопическая литература'),
(gen_random_uuid(), 'FBL', 'басня'),
(gen_random_uuid(), 'WAR_FIC', 'военная проза'),
(gen_random_uuid(), 'FAB', 'вымышленная автобиография'),
(gen_random_uuid(), 'HF', 'героическое фэнтези'),
(gen_random_uuid(), 'GOTH_LIT', 'готическая литература'),
(gen_random_uuid(), 'DET', 'детектив'),
(gen_random_uuid(), 'CH_LIT', 'детская литература'),
(gen_random_uuid(), 'DOM_FIC', 'домашняя художественная литература'),
(gen_random_uuid(), 'DRM', 'драма'),
(gen_random_uuid(), 'HIST_GEN', 'исторический жанр'),
(gen_random_uuid(), 'COMING_AGE', 'история взросления'),
(gen_random_uuid(), 'COM', 'комедия'),
(gen_random_uuid(), 'CRIME_GEN', 'криминальный жанр'),
(gen_random_uuid(), 'ROM', 'любовный роман'),
(gen_random_uuid(), 'SCI', 'наука'),
(gen_random_uuid(), 'SF', 'научная фантастика'),
(gen_random_uuid(), '1ST_PER', 'от первого лица'),
(gen_random_uuid(), 'NOVELLA', 'повесть'),
(gen_random_uuid(), 'YA_LIT', 'подростковая литература'),
(gen_random_uuid(), 'POL_SF', 'политическая фантастика'),
(gen_random_uuid(), 'POETRY', 'поэзия'),
(gen_random_uuid(), 'ADV_FIC', 'приключенческая художественная литература'),
(gen_random_uuid(), 'PSY_REAL', 'психологический реализм'),
(gen_random_uuid(), 'STORY', 'рассказ'),
(gen_random_uuid(), 'NOV', 'роман'),
(gen_random_uuid(), 'BILD_ROM', 'роман воспитания'),
(gen_random_uuid(), 'KNIGHT_ROM', 'рыцарский роман'),
(gen_random_uuid(), 'SAGA', 'сага'),
(gen_random_uuid(), 'SAT', 'сатира'),
(gen_random_uuid(), 'FAIRY', 'сказка'),
(gen_random_uuid(), 'TRAG', 'трагедия'),
(gen_random_uuid(), 'HOR', 'ужасы'),
(gen_random_uuid(), 'FIC', 'фантастика'),
(gen_random_uuid(), 'FICTION', 'фикшн'),
(gen_random_uuid(), 'PHIL', 'философия'),
(gen_random_uuid(), 'FOLK', 'фольклор'),
(gen_random_uuid(), 'FANT', 'фэнтези'),
(gen_random_uuid(), 'ART_NOV', 'художнический роман'),
(gen_random_uuid(), 'BLK_HUM', 'черный юмор'),
(gen_random_uuid(), 'EP_FANT', 'эпическое фэнтези'),
(gen_random_uuid(), 'EPOPEE', 'эпопея'),
(gen_random_uuid(), 'EPIC', 'эпос'),
(gen_random_uuid(), 'EROT_LIT', 'эротическая литература');