name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code at tagged commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reader-diary:frontend-prod ./frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reader-diary:backend-prod ./backend

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/reader-diary:frontend-prod
        docker push ${{ secrets.DOCKER_USERNAME }}/reader-diary:backend-prod

    - name: Deploy to production via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
        envs: PROD_DIR, PROD_DB_DIR
        script: |
          cd $PROD_DIR
          docker compose pull
          docker compose stop
          docker compose up -d
      env:
        PROD_DIR: ${{ secrets.PROD_DIR }}
