name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reader-diary:frontend ./frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reader-diary:backend ./backend
      
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/reader-diary:frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/reader-diary:backend

    - name: Deploy on staging server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
        envs: STAGING_DIR, STAGE_DB_DIR
        script: |
          cd $STAGING_DIR
          docker compose pull
          docker compose stop
          sudo rm -rf $STAGE_DB_DIR
          docker compose up -d
      env:
        STAGING_DIR: ${{ secrets.STAGING_DIR }}
        STAGE_DB_DIR: ${{ secrets.STAGE_DB_DIR }}
